---
title: "data_wrangling_i"
author: "TritonD"
date: "9/17/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
```

```{r}
##reads in a dataset
litters_data = read_csv(file = "./FAS_litters.csv")
```
```{r}
names(litters_data)
```
```{r}
litters_data
```


```{r}
#load in pups data
pups_data=read_csv(file = "./FAS_pups.csv")
```
```{r}
pups_data
```
```{r}
skimr::skim(litters_data)
```
```{r}
litters_data = read_csv(file = "./FAS_litters.csv",
  skip = 10, col_names = FALSE)
head(litters_data)
```
```{r}
#play with column parsing
#with a space inside variable name, need quote sign
litters_data = read_csv(file = "./FAS_litters.csv",
  col_types = cols(
    Group = col_character(),
    `Litter Number` = col_character(),
    `GD0 weight` = col_double(),
    `GD18 weight` = col_double(),
    `GD of Birth` = col_integer(),
    `Pups born alive` = col_integer(),
    `Pups dead @ birth` = col_integer(),
    `Pups survive` = col_integer()
  )
)
```

```{r}
# read in excel file
```
```{r}
mlb11_data=read_excel(path = "./mlb11.xlsx")
```
```{r}
#read in SAS
pulse_data= haven::read_sas("./public_pulse_data.sas7bdat")
```

```{r}
write_csv(mlb11_data_subset, path ="./m;b_subset.csv")
```




