---
title: "data_manipulation"
author: "TritonD"
date: "9/17/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
```

```{r}
options(tibble.print_min = 3)

litters_data = read_csv("./FAS_litters.csv",
  col_types = "ccddiiii")
litters_data = janitor::clean_names(litters_data)

pups_data = read_csv("./FAS_pups.csv",
  col_types = "ciiiii")
pups_data = janitor::clean_names(pups_data)

```

```{r}
#select, insert orders matter
select(litters_data, group, litter_number)

select(litters_data, group, litter_number, gd0_weight, starts_with("pups"))

select(litters_data, litter_number, group, gd0_weight)

select(litters_data, litter_number, group, everything())
#select everything after selecting litter_number and group

select(litters_data, -group)
#select all except group

select(litters_data, group, litter_number, gd0_weight:pups_born_alive)
#by now, haven't done anything change the data frame

select(litters_data, GROUP = group, litter_number)
#rename "group" with all capital letter

rename(litters_data, GROUP=group)
#difference with select: rename only rename that variable, don't delete other
```


##Filter
```{r}
filter(litters_data, group == "Mod8")
## double = is "does this value equal to" as a question, not given value

filter(litters_data, gd_of_birth ==20)

filter(litters_data, gd_of_birth >=20)

filter(litters_data, gd_of_birth >=20, pups_born_alive !=4)

filter(litters_data, group =="Con7"| group =="Mod8")
#"Or statement" equivalent to
filter(litters_data, group %in% c("Con7", "Mod8"))

#range
filter(litters_data, gd_of_birth >=20, gd_of_birth <=22)

filter(litters_data, gd0_weight + gd18_weight > 70)

#don't do filter(litters_data, is.na(gd0_weight)), drop null value
drop_na(litters_data)
#drop null value only in gd0_weight column
drop_na(litters_data, gd0_weight)
```


##mutate
```{r}
mutate(litters_data, wt_gain = gd18_weight -gd0_weight,
        group = str_to_lower(group)
        group = str_to_upper(group)
)
#make the string all lower cases

```

##arrange
```{r}
arrange(litters_data, pups_born_alive)

arrange(litters_data, desc(pups_born_alive))
```





